=== jiangxincode/JavaWebTest/src/test/resources/com/shengsiyuan/xml/dtd_3.dtd
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>
<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>

=== jiangxincode/JavaWebTest/shengsiyuan-java/test/resources/com/shengsiyuan/xml/dtd_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER SYSTEM "dtd_3.dtd">
<NEWSPAPER>
	<ARTICLE AUTHOR="zhanglong" DATE="2010-12-12" EDITOR="helloworld">
		<HEADLINE>hello</HEADLINE>
		<BYLINE/>
		<LEAD/>
		<BODY/>
		<NOTES/>
	</ARTICLE>
	<ARTICLE AUTHOR="zhanglong" DATE="2010-12-12" EDITOR="helloworld">
		<HEADLINE>hello</HEADLINE>
		<BYLINE/>
		<LEAD/>
		<BODY/>
		<NOTES/>
	</ARTICLE>
</NEWSPAPER>
