=== jiangxincode/JavaWebTest/kaboom-zhihu/config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT config (browser,cookie,user,targets)>

<!ELEMENT browser (type,version)>
<!ELEMENT cookie (path)>
<!ELEMENT user (username,password)>
<!ELEMENT targets (target+)>

<!ELEMENT type (#PCDATA)>
<!ELEMENT version (#PCDATA)>

<!ELEMENT path (#PCDATA)>

<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

<!ELEMENT target (method,url?,number?,shutdown?,path?)>

<!ELEMENT method (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT shutdown (#PCDATA)>

=== jiangxincode/JavaWebTest/kaboom-zhihu/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE config SYSTEM "config.dtd">
<config>

	<browser>
		<type>firefox</type>
		<version>20.10240</version>
	</browser>

	<cookie>
		<path>tmp\Cookie\cookie.txt</path>
	</cookie>

	<user>
		<username>xxxx</username>
		<password>xxxx</password>
	</user>

	<targets>
		<target>
			<method>follow</method>
			<url>https://www.zhihu.com/people/lin-bin-51/followees</url>
			<number>1000</number>
			<!-- <shutdown>true</shutdown> -->
			<!-- <remain>426</remain> -->
		</target>
		<!-- <target>
			<method>recommendations</method>
			<path>tmp\Recommendations\recommendations.txt</path>
		</target>
		<target>
			<method>users</method>
			<path>tmp\Users\users.txt</path>
		</target> -->
	</targets>
</config>
